export const CHANGE_IMAGE_INPUT='CHANGE_IMAGE_INPUT';

export const FACE_DETECTION_RUNNING='FACE_DETECTION_RUNNING';
export const FACE_DETECTION_SUCCESS='FACE_DETECTION_SUCCESS';
export const FACE_DETECTION_FAIL='FACE_DETECTION_FAIL';

export const ROUTE_CHANGE='ROUTE_CHANGE';