export const appConstants = {
CHANGE_IMAGE_INPUT: 'CHANGE_IMAGE_INPUT',

FACE_DETECTION_RUNNING: 'FACE_DETECTION_RUNNING',
FACE_DETECTION_SUCCESS: 'FACE_DETECTION_SUCCESS',
FACE_DETECTION_FAIL: 'FACE_DETECTION_FAIL',

ROUTE_CHANGE: 'ROUTE_CHANGE',

SIGN_IN: 'SIGN_IN',
SIGN_OUT: 'SIGN_OUT'
};